articleapp/urls.py
from django.views.generic import TemplateView
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

likeapp/urls.py
# likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>/', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article
from django import forms

from projectapp.models import Project


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style':'height: auto;'}))

    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


# Create your views here.
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'

class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 25
    def get_queryset(self):
        return Article.objects.order_by('?')

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Pin Create</h4>
        </div>
        <form action="{% url 'articleapp:create'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Article : {{ target_article.title }}</h4>
        </div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">
        <h1>
            {{ target_article.title }}
        </h1>
        <div style="height: 2rem;">
            <a href="#" id="like-button-{{ target_article.pk }}" onclick="likeArticle({{ target_article.pk }}, event)">
                {% if target_article.like > 0 %}
                    <i style="vertical-align:middle; font-size:1.2rem; color: #f77;" class="material-icons">
                        favorite
                    </i>
                {% else %}
                    <i style="vertical-align:middle; font-size:1.2rem; color: #f77;" class="material-icons">
                        favorite_border
                    </i>
                {% endif %}
            </a>
            <span id="like-count-{{ target_article.pk }}" style="vertical-align: middle; font-size:1.2rem;">
                {{ target_article.like }}
            </span>
        </div>
        <h5>
            {{ target_article.writer.profile.nickname }}
        </h5>
        <hr>
        <img style="width: 100%; border-radius: 1rem; margin: 2rem 0;" src="{{ target_article.image.url }}" alt="">
        <div class="text-left">
            {{ target_article.content | safe }}
        </div>

        {% if target_article.writer == user %}
            <a href="{% url 'articleapp:update' pk=target_article.pk %}"
               class="btn btn-primary rounded-pill col-3"
                style="background-color: #747474; border-color: #747474;">
                Update
            </a>
            <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
               class="btn btn-danger rounded-pill col-3">
                Delete
            </a>
        {% endif %}
        <hr>
        {% for comment in target_article.comment.all %}
            {% include 'commentapp/detail.html' with comment=comment %}
        {% endfor %}
        {% include 'commentapp/create.html' with article=target_article %}
    </div>
</div>

<script>
    function likeArticle(pk, event) {
        // Prevent the default action of the anchor tag (no page reload)
        event.preventDefault();

        // Send AJAX request to like the article
        fetch(`/likeapp/article/like/${pk}/`, {
            method: 'GET',
            headers: {
                'X-CSRFToken': getCookie('csrftoken')
            }
        })
        .then(response => response.json())
        .then(data => {
            console.log(data);  // Log the response from the server

            // Update the like button icon based on the response
            const likeButton = document.getElementById(`like-button-${pk}`);
            const likeCount = document.getElementById(`like-count-${pk}`);

            if (data.status === 'liked') {
                likeButton.innerHTML =
                    `<i style="vertical-align:middle; font-size:1.2rem; color: #f77;" class="material-icons">favorite</i>`;
            } else {
                likeButton.innerHTML =
                    `<i style="vertical-align:middle; font-size:1.2rem; color: #f77;" class="material-icons">favorite_border</i>`;
            }

            // Update the like count
            likeCount.innerText = data.like_count;

            // Display the success message
            displayMessage(data.message);
        })
        .catch(error => console.error('Error:', error));
    }

    // Function to get the CSRF token from the cookie
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    // Function to display the message
    function displayMessage(message) {
        const messageContainer = document.createElement('div');
        messageContainer.classList.add('text-center', 'message-container');

        // Create the message element and set its text content
        const messageElement = document.createElement('div');
        messageElement.classList.add('btn', 'btn-success', 'rounded-pill', 'px-5', 'my-3', 'fade-message');
        messageElement.textContent = message;  // Use textContent to ensure the message is treated as plain text

        // Append the message element to the container
        messageContainer.appendChild(messageElement);
        document.body.appendChild(messageContainer);

        // Apply fade-out effect after 3 seconds
        setTimeout(() => {
            messageElement.style.opacity = '0';  // Start fade-out
            messageElement.style.transition = 'opacity 1s ease-out';  // Smooth transition
            setTimeout(() => {
                messageContainer.remove();  // Remove the message from DOM after fade-out
            }, 1000);  // Remove after 1 second of fading
        }, 1000);  // Delay fade-out by 3 seconds
    }
</script>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>
    .container {
        padding: 0;
        margin: 0 auto;
        position: relative; /* Ensure positioning context for MagicGrid */
    }

    .container a {
        width: 45%;
        max-width: 250px;
        margin-bottom: 15px; /* Space between articles */
    }

    .container div {
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }

    </style>

    {% if article_list %}
    <div class="container">
        {% for article in article_list %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %}
        </a>
        {% endfor %}
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>
    <script>
        // Make sure MagicGrid is initialized after the images have loaded
        window.onload = function() {
            let magicGrid = new MagicGrid({
                container: '.container',
                animate: true,
                gutter: 12,  // Set gutter spacing, adjust as needed
                static: true,
                useMin: true
            });

            magicGrid.listen();
        };
    </script>

    {% else %}
    <div class="text-center">
        <h1>No Pin</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}
    <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-2">
            Create Pin
        </a>
    </div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Pin Update</h4>
        </div>
        <form action="{% url 'articleapp:update' pk=target_article.pk  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}